yt-dlp --write-auto-sub --skip-download 07mdDob7bVk
yt-dlp --write-auto-sub --skip-download 1AsrVuejU5E
yt-dlp --write-auto-sub --skip-download 64hpbxkKp8Y
yt-dlp --write-auto-sub --skip-download 7HPrZ2pugTE
yt-dlp --write-auto-sub --skip-download 8sNe50wgJ_g
yt-dlp --write-auto-sub --skip-download 93zWQG2lgII
yt-dlp --write-auto-sub --skip-download 9r27os7I_sU
yt-dlp --write-auto-sub --skip-download azhjl2PB_bw
yt-dlp --write-auto-sub --skip-download bPFtgCvR1A0
yt-dlp --write-auto-sub --skip-download bYodzlh5p9A
yt-dlp --write-auto-sub --skip-download c1VSG82FjK8
yt-dlp --write-auto-sub --skip-download g-3cT32d_uo
yt-dlp --write-auto-sub --skip-download gdXVGdmtGE4
yt-dlp --write-auto-sub --skip-download G-SOZZDhB7U
yt-dlp --write-auto-sub --skip-download HeeYadnw1Yo
yt-dlp --write-auto-sub --skip-download I6qKBdKZlsE
yt-dlp --write-auto-sub --skip-download jbhGzArIcbQ
yt-dlp --write-auto-sub --skip-download lbsfCvZTUzA
yt-dlp --write-auto-sub --skip-download mT5M_ZJCdNc
yt-dlp --write-auto-sub --skip-download O3n-JhktFOw
yt-dlp --write-auto-sub --skip-download rIJ6Sy6RDNk
yt-dlp --write-auto-sub --skip-download tHY-fjo4gbc
yt-dlp --write-auto-sub --skip-download U7Orn4cILAE
yt-dlp --write-auto-sub --skip-download UOuTeIZm72U
yt-dlp --write-auto-sub --skip-download uRWnJ4IFkEg
yt-dlp --write-auto-sub --skip-download WgVHkK0uz9k
yt-dlp --write-auto-sub --skip-download XxCSNK7hgDU
yt-dlp --write-auto-sub --skip-download yHqmNRvc0So
yt-dlp --write-auto-sub --skip-download zflTpkQjx2U
yt-dlp --write-auto-sub --skip-download zU17Q-HmvbU
