yt-dlp --write-auto-sub --skip-download 2KVuHILxUtc
yt-dlp --write-auto-sub --skip-download 2PeTcGSaakQ
yt-dlp --write-auto-sub --skip-download 3iKmSWvYDro
yt-dlp --write-auto-sub --skip-download 4orKiu6vLRI
yt-dlp --write-auto-sub --skip-download 8htr4HMCLQg
yt-dlp --write-auto-sub --skip-download 8Vj-I2xDaIQ
yt-dlp --write-auto-sub --skip-download 9DURUz8LVQc
yt-dlp --write-auto-sub --skip-download A9FiAxKou8s
yt-dlp --write-auto-sub --skip-download Ayk2hKUVjbM
yt-dlp --write-auto-sub --skip-download E7Rg0q7oMw4
yt-dlp --write-auto-sub --skip-download eCV9SPOJNT8
yt-dlp --write-auto-sub --skip-download -HijJQuMXuw
yt-dlp --write-auto-sub --skip-download i-gux9Fmrek
yt-dlp --write-auto-sub --skip-download IPpQ9hoglLQ
yt-dlp --write-auto-sub --skip-download joTaZtwzBg4
yt-dlp --write-auto-sub --skip-download KZevsIWuTxo
yt-dlp --write-auto-sub --skip-download lC0gkEnulRI
yt-dlp --write-auto-sub --skip-download lFHV-KQ4KRo
yt-dlp --write-auto-sub --skip-download lJSeZqzEW8E
yt-dlp --write-auto-sub --skip-download LY3CYKvOYhA
yt-dlp --write-auto-sub --skip-download OLYhSauHSCA
yt-dlp --write-auto-sub --skip-download -OQbj06KKkc
yt-dlp --write-auto-sub --skip-download pz9_-jgTgEc
yt-dlp --write-auto-sub --skip-download QGyMQB6MYJQ
yt-dlp --write-auto-sub --skip-download QihAOAUuQT4
yt-dlp --write-auto-sub --skip-download -q-ZEtVBuhY
yt-dlp --write-auto-sub --skip-download ukHMatKIpK0
yt-dlp --write-auto-sub --skip-download v1uFfqkLdQU
yt-dlp --write-auto-sub --skip-download zacsKU0zk2k
yt-dlp --write-auto-sub --skip-download zei2EgFAufY
